### ISSUE TITLE
suggestion : be more visible

### ISSUE THREAD

**Issue by kaktus40** [alberto-acevedo/cesium-navigation#1]
Hello,
thanks for this great plugin.  Could you be more visible and add your plugin in [cesium plugin list] (https://github.com/AnalyticalGraphicsInc/cesium-plugins-list) ?

**Comment by alberto-acevedo** [comment]
I'm in the process of adding the plugin to the cesium plugin list. 
Thank you for your pull request. I forgot to push the package.json file. I will merge your changes tonight.
