### ISSUE TITLE
CSS Style a not only for class

### ISSUE THREAD

**Issue by strech345** [alberto-acevedo/cesium-navigation#18]
please replace 
.markdown u, a : hover {
	text - decoration : underline
}

to 
.markdown u, .markdown a : hover {
	text - decoration : underline
}

ohterwise it replace for all a

**Comment by alberto-acevedo** [comment]
strech345,

I will make the correction. Are you using the latest version 1.0.2 of the plugin that uses the mixin design pattern?

Thanks,

Alberto

**Comment by strech345** [comment]
How does it work without having a css file?
Im wondering, that there is no css to include.

**Comment by Larcius** [comment]
The project contains several "less" files which are then included in the built javascript file. This is done by using the nodejs package "require-less" (https://github.com/guybedford/require-less).
It works regardless whether your are using the mixin as standalone or via requirejs.

Just have a look at the [https://alberto-acevedo.github.io/cesium-navigation/](example), open your developer tools and check the head section. There you can find the appended style
`<style type="text/css">.full-window{...`

**Comment by alberto-acevedo** [comment]
The markdown was modified in the styles. Closing this issue.
