### ISSUE TITLE
Improve documentation around options

### ISSUE THREAD

**Issue by rowanwins** [alberto-acevedo/cesium-navigation#22]
Gday,

Thanks for a great plugin, very handy indeed!

One thing I noticed in regards to the doco is that is says you can pass in an options object although nothing describes what options are.

In particular I was looking for options to allow me to turn various bits off (eg the zoom buttons).

Anyway just a suggestion :)

Thanks
Rowan

**Comment by alberto-acevedo** [comment]
Rowan,

I just started adding properties to the options object. Right now the only property that the options take is the setting of the default view when clicking the reset view button located between the zoom buttons. The next property to add to the options will be the setting of the visibility of the navigation. I like your suggestion.  I will expand the property to allow the setting of visibility of individual components.

Thanks,

Alberto

**Comment by alberto-acevedo** [comment]
Rowan,

I just committed to master the following options that you requested.

Setting the options for the plugin:

defaultResetView --> option used to set a default view when resetting the map view with the reset navigation 
control. Values accepted are of type Cesium.Cartographic and Cesium.Rectangle.

enableCompass --> option used to enable or disable the compass. Values accepted are true for enabling and false to disable. The default is true.

enableZoomControls --> option used to enable or disable the zoom controls. Values accepted are true for enabling and false to disable. The default is true.

enableDistanceLegend --> option used to enable or disable the distance legend. Values accepted are true for enabling and false to disable. The default is true.

More options will be set in future releases of the plugin.

Example: how to disable the zoom controls and the distance legend:

var options = {};
options.defaultResetView = Cesium.Rectangle.fromDegrees(71, 3, 90, 14);
options.enableCompass= true;
options.enableZoomControls= false;
options.enableDistanceLegend= false;
cesiumViewer.extend(Cesium.viewerCesiumNavigationMixin, options);

Thanks,

Alberto

**Comment by alberto-acevedo** [comment]
v1.1.3 is has the options requested by Rowan. Closing this issue.

**Comment by rowanwins** [comment]
Thanks @alberto-acevedo
