### ISSUE TITLE
node Building.js encounter some errors

### ISSUE THREAD

**Issue by fxkulou** [alberto-acevedo/cesium-navigation#23]
I have installed npm ,nodejs and configured them,but when I use the command "node building.js", I get the response below:
fs.js:839
     return binding.lstat(pathModule._makeLong(path));
Error:ENOENT:no such file or directory,lstat'C:\Users|Administrator\Source'
    at Error(native)
   at Object.fs.lstatSync(fs.js:839:18)
          ................................
.............................
at Module.load(module.js:343:32)
at Function.Module._load(module.js:300:12)
at Function.Module.runMain(module.js:441:10)

**Comment by Larcius** [comment]
as the error states there is no file _building.js_.
The build file is named **build.js** (see _How to build it?_ of _README.md_).

@alberto-acevedo Please close this issue

**Comment by fxkulou** [comment]
Sorry,I have make a writing mistake,is node build.js,and i ensure the file exists. @Larcius

**Comment by fxkulou** [comment]
I will change this problem to the cesium forum,thanks @Larcius
