### ISSUE TITLE
Styles Contained to plugin

### ISSUE THREAD

**Issue by Joebh** [alberto-acevedo/cesium-navigation#29]
To be used as plugin, the styles like .modal and .modal-heading that are included in the standalone build should be removed.

The only styles included should only affect the plugin.

**Comment by alberto-acevedo** [comment]
I agree.  The modals are remanent styles from the Terriajs project You are welcome to contribute if you already have a working modified style without the modals. Thanks you.

**Comment by alberto-acevedo** [comment]
Joebh,

There is a new release version 1.1.6 of the plugin. This version doesn't have any modal styles. Thank you for letting us know about the issue.
