### ISSUE TITLE
Standalone files

### ISSUE THREAD

**Issue by theranch** [alberto-acevedo/cesium-navigation#31]
In your Examples/standalone.html file you have the following tag in the html.
 <script src="dist/standalone/viewerCesiumNavigationMixin.min.js"></script>

This viewerCesiumNavigationMixin.min.js file is not in the zip file. Where is this coming from? 

Thanks!

**Comment by Larcius** [comment]
you need to build the project in order to get the files located in `dist`
To do so simply run the following two commands:
`npm install`
`node build.js`

**Comment by theranch** [comment]
I don't have node installed and am not permitted to install it on my machine. I should have noted that in my original comment.

**Comment by Larcius** [comment]
i don't know how to develop software without having the permission to install new software/tools.
however, you can check out the example page (http://alberto-acevedo.github.io/cesium-navigation/)
and then you will find the dependency you are looking for:
http://alberto-acevedo.github.io/cesium-navigation/dist/standalone/viewerCesiumNavigationMixin.min.js

**Comment by alberto-acevedo** [comment]
theranch,

This is not an issue of the plugin.  I'm getting ready to close this issue.  If you have any other issue please let me know.

**Comment by theranch** [comment]
My issue was that the Examples show "standalone" but you need to build it this code in order to use the standalone. I don't have the mechanism to build this code at my job. That's all I'm saying. All you would need to do is provide the actual viewerCesiumNavigationMixin.js to the source so that people can track any updates and get the latest version without having to dig through and find it.
