### ISSUE TITLE
changing css style and position of controls

### ISSUE THREAD

**Issue by am2222** [alberto-acevedo/cesium-navigation#41]
Hi,
Is there any way to change css style and position of the controls without changing them in the source?

**Comment by alberto-acevedo** [comment]
Majid Hojati ,

The style is embedded in the plugin. You have to make your changes to the embedded style and positions and then rebuild the plugin.  Changing programatically the position and styles of the controls will require the adding of functions (API) .

Alberto

-----Original Message-----

**Comment by am2222** [comment]
@alberto-acevedo thanks so much, 
It would be great if it was possible to do it using API. 
Anyway thanks for the answer
