### ISSUE TITLE
Compass partially overlaps Cesium infobox

### ISSUE THREAD

**Issue by raevskiy** [alberto-acevedo/cesium-navigation#8]
Compass partially overlaps Cesium infobox, "N" is hidden, while the rest of the compass is visible
![compass](https://cloud.githubusercontent.com/assets/15690601/12671100/76c376e6-c67e-11e5-8af4-fdc398ac9efa.jpg)

**Comment by raevskiy** [comment]
The same is true for "Zoom In", "Zoom Out" and "Reset View"

**Comment by Larcius** [comment]
the "N" is not hidden but it's just invisible because the font color is the same as the background color of that box.

However, I agree with you that the info box should be on top.

To generalize this issue:
I think the whole compas should be a ViewerMixin instead of creating and placing the DIV elements manually and hence causing unexpected side effects.
By this the integration/usage would be much simpler because one could simply use Viewer.extend(mixin, options) to add the compass to any view while providing the possibility to change some properties, e.g. show/hide legend/orbit/compass/zoom, via "options".
Of course this is not a small change but in my opinion it's worth it.

**Comment by alberto-acevedo** [comment]
Hi Larcius,

I agree that the navigation plugin needs to be wrapped in a way that will make it easier to manipulate its style properties, like for example the setting of its visibility. The hardest part when making this plugin was gluing all the separate parts together with the styles. I need to learn more about ViewerMixin, so I don't know how big would be the impact in the existing plugin source code. Based on your experience in ViewerMixin, how big would be the impact?  Meanwhile we need to find a quick solution for the overlapping issue that @raevskiy  is having. It could be related to the z-index. A possible quick solution would be to allow the user of the plugin to set the plugin visibility to false when opening the Cesium info box. Thank you for your contribution.

**Comment by Larcius** [comment]
adding CSS style
`
.cesium-infoBox {
z-index: 1
}
`
should fix that issue for the moment but it's rather a quick&dirty workaround.

So far I only did one ViewerMixin that added a button allowing the user to meassure distances of paths.
So I know it's possible (and easy) to add elements to the view and listen to the events affecting that view.
To give a precise estimation of how much work it is to convert this plugin to a ViewerMixin I have to further analyse your plugin. At the moment I'm a bit busy but in three weeks I got time.

**Comment by alberto-acevedo** [comment]
The use of ViewerMixin is a good idea but it think it represents a complete redesign of the whole plugin. The main  intention of the plugin was to extra\ct and encapsulate the great capabilities of the existing navigator from Terriajs. I consider the answer from Larcius as an aceptable fix to this issue.

**Comment by Larcius** [comment]
I've converted it to a viewer mixin and changed the building procedure:
https://github.com/Larcius/cesium-navigation

By this a single file including the CSS is generated and can be easily used. It is also possible to use it as an AMD module. Have a look at the examples:
Source: https://github.com/Larcius/cesium-navigation/tree/viewer-mixin/Examples
Watch: http://larcius.github.io/cesium-navigation/

P.S.: The overlapping bug was fixed without any additional work ;-)

**Comment by alberto-acevedo** [comment]
Larcius,
 
 Great job. I will test the plugin with the mixin in my project at work. I will let you know if I find any issues.

Thanks,

Alberto
   
 
   
 
  
 
 -----Original Message-----
